---
abstract: 'JSON RPC 2.0 over HTTP'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Exception: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.42, CPAN::Meta::Converter version 2.133380'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-JSONRPC2
provides:
  Mojolicious::Plugin::JSONRPC2:
    file: lib/Mojolicious/Plugin/JSONRPC2.pm
    version: v1.0.0
requires:
  JSON::RPC2: v0.4.0
  JSON::XS: 0
  Mojolicious: 0
  perl: 5.010001
  version: 0.77
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v1.0.0
